theme: jekyll-theme-minimal
title: "Máximo Sangiácomo"
description: Página personal 
url: https://github.com/msangia/msangia.github.io/raw/main/MSangia_CVeng.pdf
twitter: msangia
logo: /assets/img/kykcolor.jpg
show_downloads: true
google_analytics:   
